USE [master]
GO

/****** Object:  Database [FCDatabase]    Script Date: 20.10.2017 15:26:18 ******/
CREATE DATABASE [FCDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FCDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FCDatabase.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FCDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FCDatabase_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FCDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FCDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FCDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FCDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FCDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FCDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FCDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [FCDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FCDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FCDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FCDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FCDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FCDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FCDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FCDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FCDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FCDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FCDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FCDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FCDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FCDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FCDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FCDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FCDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FCDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FCDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [FCDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [FCDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FCDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FCDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FCDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FCDatabase] SET  READ_WRITE 
GO


